# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
        backend "azurerm" {
            resource_group_name  = "tf-str-29"
            storage_account_name = "tfstrbck29"
            container_name       = "terraform-state"
            key                  = "..terraform.tfstate"
        }
    }
